In [10]:
import requests
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from dotenv import load_dotenv
import time

Sites onde tirei as informações

"https://www.kaggle.com/datasets/rounakbanik/the-movies-dataset?resource=download&select=movies_metadata.csv"

"https://datasets.imdbws.com/"

"https://www.themoviedb.org/"

In [9]:
# Leitura dos arquivos csv e tsv

df_movies = pd.read_csv('movies_metadata.csv')

df_basics = pd.read_table('title.basics.tsv.gz')

df_rating = pd.read_table('title.ratings.tsv.gz')

C:\Users\User\AppData\Local\Temp\ipykernel_12040\3404999718.py:3: DtypeWarning: Columns (0: popularity) have mixed types. Specify dtype option on import or set low_memory=False.
  df_movies = pd.read_csv('movies_metadata.csv')

In [11]:
# Analisamos todas as colunas
df_movies.columns

# Escolhemos apenas as colunas uteis para analise
colunas_uteis = ['id', 'imdb_id', 'title', 'budget', 'revenue', 'release_date', 'runtime', 'popularity', 'vote_average', 'vote_count', 'genres']

# Substituimos o dataset apenas com as colunas uteis
df_movies = df_movies[colunas_uteis]

In [12]:
# Analisamos todas as colunas
df_basics.columns

# Escolhemos apenas as colunas uteis para analise
colunas_uteis = ['tconst', 'titleType', 'primaryTitle', 'startYear', 'runtimeMinutes', 'genres']

# Substituimos o dataset apenas com as colunas uteis
df_basics = df_basics[colunas_uteis]

In [13]:
# Filtrando por apenas filmes porque possui serie e curtas
df_basics = df_basics[df_basics['titleType'] == 'movie']

# Dropando a coluna porque esta filtrado para apenas filmes
df_basics = df_basics.drop('titleType', axis=1)

In [14]:
# Analise dos nulos antes do tratamento
print(df_movies.isnull().sum(), '\n')
print(df_basics.isnull().sum(), '\n')
print(df_rating.isnull().sum(), '\n')

id                0
imdb_id          17
title             6
budget            0
revenue           6
release_date     87
runtime         263
popularity        5
vote_average      6
vote_count        6
genres            0
dtype: int64

tconst            0
primaryTitle      3
startYear         0
runtimeMinutes    0
genres            0
dtype: int64

tconst           0
averageRating    0
numVotes         0
dtype: int64

In [15]:
# Dropando valores nulos em colunas essenciais

df_basics = df_basics.dropna(subset=['primaryTitle'])

df_movies = df_movies.dropna(subset=['imdb_id', 'title', 'release_date', 'runtime'])

In [16]:
# Analise dos nulos após tratamento
print(df_movies.isnull().sum(), '\n')
print(df_basics.isnull().sum(), '\n')
print(df_rating.isnull().sum(), '\n')

id              0
imdb_id         0
title           0
budget          0
revenue         0
release_date    0
runtime         0
popularity      0
vote_average    0
vote_count      0
genres          0
dtype: int64

tconst            0
primaryTitle      0
startYear         0
runtimeMinutes    0
genres            0
dtype: int64

tconst           0
averageRating    0
numVotes         0
dtype: int64

In [17]:
# Renomeando colunas para  merge

df_basics.rename(columns={'tconst': 'imdb_id'}, inplace=True)

df_rating.rename(columns={'tconst': 'imdb_id'}, inplace=True)

In [18]:
# Removemos a coluna starYear porque usaremos a coluna release_date do df_movies

df_basics = df_basics.drop('startYear', axis=1)

# Removemos a coluna runtimeMinutes porque usaremos a coluna runtime de df_movies

df_basics = df_basics.drop('runtimeMinutes', axis=1)

# Removemos a coluna genres de df_movies porque esta em json

df_movies = df_movies.drop('genres', axis=1)

# Removemos as colunas de vote do df_movies por causa que podem estar desatualizadas enquanto as do df_rating são atualizadas pelo imdb

df_movies = df_movies.drop(columns=['vote_average', 'vote_count'])

In [19]:
# Visualizando como ficou o dataframe
df_movies.head()

,id,imdb_id,title,budget,revenue,release_date,runtime,popularity
0,862,tt0114709,Toy Story,30000000,373554033.0,1995-10-30,81.0,21.946943
1,8844,tt0113497,Jumanji,65000000,262797249.0,1995-12-15,104.0,17.015539
2,15602,tt0113228,Grumpier Old Men,0,0.0,1995-12-22,101.0,11.7129
3,31357,tt0114885,Waiting to Exhale,16000000,81452156.0,1995-12-22,127.0,3.859495
4,11862,tt0113041,Father of the Bride Part II,0,76578911.0,1995-02-10,106.0,8.387519

In [20]:
# Visualizando como ficou o dataframe
df_rating.head()

     imdb_id  averageRating  numVotes
0  tt0000001            5.7      2211
1  tt0000002            5.4       319
2  tt0000003            6.4      2344
3  tt0000004            5.1       192
4  tt0000005            6.2      3059

In [21]:
# Visualizando como ficou o dataframe
df_basics.head()

       imdb_id                   primaryTitle                      genres
8    tt0000009                     Miss Jerry                     Romance
144  tt0000147  The Corbett-Fitzsimmons Fight      Documentary,News,Sport
498  tt0000502                       Bohemios                          \N
570  tt0000574    The Story of the Kelly Gang  Action,Adventure,Biography
587  tt0000591               The Prodigal Son                       Drama

In [22]:
# Começando o merge
# Primeiro merge entre rating e movies
df_final = pd.merge(df_movies, df_rating, on='imdb_id', how='inner')

# Segundo merge que junto o basics apenas com as colunas imdb e genres
df_final = pd.merge(df_final, df_basics[['imdb_id', 'genres']], on='imdb_id', how='inner')

In [23]:
# Verificando o dataframe combinado
df_final.head()

,id,imdb_id,title,budget,revenue,release_date,runtime,popularity,averageRating,numVotes,genres
0,862,tt0114709,Toy Story,30000000,373554033.0,1995-10-30,81.0,21.946943,8.3,1176535,"Adventure,Animation,Comedy"
1,8844,tt0113497,Jumanji,65000000,262797249.0,1995-12-15,104.0,17.015539,7.1,414470,"Adventure,Comedy,Family"
2,15602,tt0113228,Grumpier Old Men,0,0.0,1995-12-22,101.0,11.7129,6.7,31720,"Comedy,Romance"
3,31357,tt0114885,Waiting to Exhale,16000000,81452156.0,1995-12-22,127.0,3.859495,6.0,14008,"Comedy,Drama,Romance"
4,11862,tt0113041,Father of the Bride Part II,0,76578911.0,1995-02-10,106.0,8.387519,6.1,45316,"Comedy,Family,Romance"

In [24]:
# Verificando orçamentos e faturamentos zerados
# Convertemos primeiro para float caso não esteja
df_final['budget'] = df_final['budget'].astype(float)
df_final['revenue'] = df_final['revenue'].astype(float)

qtd_zeros_budget = (df_final['budget'] == 0).sum()
qtd_zeros_revenue = (df_final['revenue'] == 0).sum()

print(f"Orçamentos zerados: {qtd_zeros_budget}")
print(f"Faturamentos zerados: {qtd_zeros_revenue}")

# Verificando as strings nulas do IMDb (\N)
qtd_zeros_genres = (df_final['genres'] == '\\N').sum()

print(f"Gêneros como '\\N': {qtd_zeros_genres}")

Orçamentos zerados: 30423
Faturamentos zerados: 31513
Gêneros como '\N': 12

In [25]:
# Escolhemos tirar todos os filmes que não possuem orçamento e faturamento
df_final = df_final[(df_final['budget'] > 0) & (df_final['revenue'] > 0)]

# Limpando os falsos nulos do IMDb
df_final = df_final[df_final['genres'] != '\\N']

# Mexemos também no runtime para não ter zeros
df_final['runtime'] = df_final['runtime'].astype(float)
df_final = df_final[df_final['runtime'] > 0]

In [26]:
# Dataset após organização
df_final.head()

,id,imdb_id,title,budget,revenue,release_date,runtime,popularity,averageRating,numVotes,genres
0,862,tt0114709,Toy Story,30000000.0,373554033.0,1995-10-30,81.0,21.946943,8.3,1176535,"Adventure,Animation,Comedy"
1,8844,tt0113497,Jumanji,65000000.0,262797249.0,1995-12-15,104.0,17.015539,7.1,414470,"Adventure,Comedy,Family"
3,31357,tt0114885,Waiting to Exhale,16000000.0,81452156.0,1995-12-22,127.0,3.859495,6.0,14008,"Comedy,Drama,Romance"
5,949,tt0113277,Heat,60000000.0,187436818.0,1995-12-15,170.0,17.924927,8.3,806505,"Action,Crime,Drama"
8,9091,tt0114576,Sudden Death,35000000.0,64350171.0,1995-12-22,106.0,5.23158,5.9,39661,"Action,Crime,Thriller"

In [27]:
# Vendo as informações do dataset
df_final.info()

<class 'pandas.DataFrame'>
Index: 5355 entries, 0 to 38846
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             5355 non-null   str
 1   imdb_id        5355 non-null   str
 2   title          5355 non-null   str
 3   budget         5355 non-null   float64
 4   revenue        5355 non-null   float64
 5   release_date   5355 non-null   str
 6   runtime        5355 non-null   float64
 7   popularity     5355 non-null   object
 8   averageRating  5355 non-null   float64
 9   numVotes       5355 non-null   int64
 10  genres         5355 non-null   str
dtypes: float64(4), int64(1), object(1), str(5)
memory usage: 502.0+ KB

In [28]:
# Convertendo release_date em date e popularity em float

df_final['release_date'] = pd.to_datetime(df_final['release_date'], format='%Y-%m-%d')

df_final['popularity'] = df_final['popularity'].astype(float)

In [29]:
# Vendo se os tipos estão agora certos
df_final.info()

<class 'pandas.DataFrame'>
Index: 5355 entries, 0 to 38846
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             5355 non-null   str
 1   imdb_id        5355 non-null   str
 2   title          5355 non-null   str
 3   budget         5355 non-null   float64
 4   revenue        5355 non-null   float64
 5   release_date   5355 non-null   datetime64[us]
 6   runtime        5355 non-null   float64
 7   popularity     5355 non-null   float64
 8   averageRating  5355 non-null   float64
 9   numVotes       5355 non-null   int64
 10  genres         5355 non-null   str
dtypes: datetime64[us](1), float64(5), int64(1), str(4)
memory usage: 502.0 KB

In [39]:
# Configurando a API do TMDB

load_dotenv("tmdb.env")
API_KEY = os.getenv("TMDB_API_KEY")

if not API_KEY:
    raise ValueError("TMDB_API_KEY não encontrada no .env. Verifique o arquivo.")

BASE_URL = "https://api.themoviedb.org/3"

In [40]:
# Função para buscar detalhes de um filme pelo id do TMDB
# Com timeout e retry: sem isso, uma única requisição que trava
# pode deixar o loop inteiro parado para sempre

def buscar_detalhes_filme(tmdb_id, max_tentativas=2, timeout=8):
    url = f"{BASE_URL}/movie/{int(tmdb_id)}"
    params = {"api_key": API_KEY, "language": "en-US"}

    for tentativa in range(max_tentativas):
        try:
            return requests.get(url, params=params, timeout=timeout)
        except requests.exceptions.RequestException:
            if tentativa < max_tentativas - 1:
                time.sleep(1)
                continue
            return None
    return None

In [41]:
# Extração principal: para cada filme, busca franquia, estúdio, idioma e país
# Salva em cache (tmdbAPI_dados.csv) para não precisar chamar a API de novo
# toda vez que o notebook for reaberto

if os.path.exists("tmdbAPI_dados.csv"):
    df_api = pd.read_csv("tmdbAPI_dados.csv")
    print("Carregado do cache, sem chamar a API.")

else:
    resultados = []
    total = len(df_final)
    falhas = 0
    inicio = time.time()

    for i, row in df_final.iterrows():
        resp = buscar_detalhes_filme(row["id"])

        if resp is not None and resp.status_code == 200:
            dados = resp.json()

            colecao = dados.get("belongs_to_collection")
            franquia = colecao["name"] if colecao else None

            estudios = dados.get("production_companies", [])
            estudio_principal = estudios[0]["name"] if estudios else None

            paises = dados.get("production_countries", [])
            pais_producao = ", ".join([p["name"] for p in paises]) if paises else None

            resultados.append({
                "id": row["id"],
                "franquia": franquia,
                "is_franchise": colecao is not None,
                "estudio_principal": estudio_principal,
                "original_language": dados.get("original_language"),
                "production_countries": pais_producao,
                "status": dados.get("status"),
            })

        else:
            falhas += 1
            resultados.append({
                "id": row["id"],
                "franquia": None,
                "is_franchise": None,
                "estudio_principal": None,
                "original_language": None,
                "production_countries": None,
                "status": None,
            })

        if (i + 1) % 10 == 0 or (i + 1) == total:
            decorrido = time.time() - inicio
            print(f"Progresso: {i + 1}/{total} | falhas: {falhas} | tempo: {decorrido:.0f}s")

        time.sleep(0.03)

    df_api = pd.DataFrame(resultados)
    df_api.to_csv("tmdbAPI_dados.csv", index=False)
    print(f"\nConcluído e salvo em cache. {falhas} filme(s) sem dados.")

Progresso: 10/5355 | falhas: 0 | tempo: 24s
Progresso: 20/5355 | falhas: 0 | tempo: 32s
Progresso: 70/5355 | falhas: 0 | tempo: 60s
Progresso: 80/5355 | falhas: 0 | tempo: 66s
Progresso: 90/5355 | falhas: 0 | tempo: 72s
Progresso: 140/5355 | falhas: 0 | tempo: 94s
Progresso: 160/5355 | falhas: 0 | tempo: 133s
Progresso: 170/5355 | falhas: 0 | tempo: 137s
Progresso: 180/5355 | falhas: 0 | tempo: 145s
Progresso: 210/5355 | falhas: 0 | tempo: 170s
Progresso: 240/5355 | falhas: 0 | tempo: 187s
Progresso: 270/5355 | falhas: 0 | tempo: 221s
Progresso: 330/5355 | falhas: 0 | tempo: 277s
Progresso: 360/5355 | falhas: 0 | tempo: 297s
Progresso: 400/5355 | falhas: 0 | tempo: 320s
Progresso: 430/5355 | falhas: 0 | tempo: 338s
Progresso: 470/5355 | falhas: 0 | tempo: 363s
Progresso: 480/5355 | falhas: 0 | tempo: 366s
Progresso: 490/5355 | falhas: 0 | tempo: 376s
Progresso: 520/5355 | falhas: 0 | tempo: 400s
Progresso: 540/5355 | falhas: 0 | tempo: 415s
Progresso: 580/5355 | falhas: 0 | tempo: 446s
Progresso: 600/5355 | falhas: 0 | tempo: 454s
Progresso: 640/5355 | falhas: 0 | tempo: 462s
Progresso: 700/5355 | falhas: 0 | tempo: 481s
Progresso: 730/5355 | falhas: 0 | tempo: 489s
Progresso: 750/5355 | falhas: 0 | tempo: 497s
Progresso: 760/5355 | falhas: 0 | tempo: 501s
Progresso: 770/5355 | falhas: 0 | tempo: 506s
Progresso: 810/5355 | falhas: 0 | tempo: 527s
Progresso: 840/5355 | falhas: 0 | tempo: 544s
Progresso: 860/5355 | falhas: 0 | tempo: 557s
Progresso: 880/5355 | falhas: 0 | tempo: 584s
Progresso: 900/5355 | falhas: 0 | tempo: 592s
Progresso: 920/5355 | falhas: 0 | tempo: 600s
Progresso: 950/5355 | falhas: 0 | tempo: 620s
Progresso: 970/5355 | falhas: 0 | tempo: 624s
Progresso: 980/5355 | falhas: 0 | tempo: 633s
Progresso: 990/5355 | falhas: 0 | tempo: 646s
Progresso: 1040/5355 | falhas: 0 | tempo: 698s
Progresso: 1070/5355 | falhas: 0 | tempo: 724s
Progresso: 1130/5355 | falhas: 0 | tempo: 742s
Progresso: 1140/5355 | falhas: 0 | tempo: 757s
Progresso: 1150/5355 | falhas: 0 | tempo: 767s
Progresso: 1160/5355 | falhas: 0 | tempo: 774s
Progresso: 1170/5355 | falhas: 0 | tempo: 779s
Progresso: 1180/5355 | falhas: 0 | tempo: 805s
Progresso: 1190/5355 | falhas: 0 | tempo: 810s
Progresso: 1200/5355 | falhas: 0 | tempo: 831s
Progresso: 1210/5355 | falhas: 0 | tempo: 841s
Progresso: 1260/5355 | falhas: 0 | tempo: 871s
Progresso: 1280/5355 | falhas: 0 | tempo: 888s
Progresso: 1290/5355 | falhas: 0 | tempo: 891s
Progresso: 1300/5355 | falhas: 0 | tempo: 910s
Progresso: 1350/5355 | falhas: 0 | tempo: 943s
Progresso: 1400/5355 | falhas: 0 | tempo: 969s
Progresso: 1440/5355 | falhas: 0 | tempo: 987s
Progresso: 1480/5355 | falhas: 0 | tempo: 1003s
Progresso: 1510/5355 | falhas: 0 | tempo: 1022s
Progresso: 1560/5355 | falhas: 0 | tempo: 1064s
Progresso: 1570/5355 | falhas: 0 | tempo: 1073s
Progresso: 1580/5355 | falhas: 0 | tempo: 1077s
Progresso: 1590/5355 | falhas: 0 | tempo: 1087s
Progresso: 1610/5355 | falhas: 0 | tempo: 1099s
Progresso: 1630/5355 | falhas: 0 | tempo: 1113s
Progresso: 1680/5355 | falhas: 0 | tempo: 1145s
Progresso: 1690/5355 | falhas: 0 | tempo: 1150s
Progresso: 1700/5355 | falhas: 0 | tempo: 1153s
Progresso: 1760/5355 | falhas: 0 | tempo: 1195s
Progresso: 1770/5355 | falhas: 0 | tempo: 1205s
Progresso: 1800/5355 | falhas: 0 | tempo: 1235s
Progresso: 1810/5355 | falhas: 0 | tempo: 1255s
Progresso: 1820/5355 | falhas: 0 | tempo: 1264s
Progresso: 1830/5355 | falhas: 0 | tempo: 1281s
Progresso: 1840/5355 | falhas: 0 | tempo: 1294s
Progresso: 1850/5355 | falhas: 0 | tempo: 1310s
Progresso: 1880/5355 | falhas: 0 | tempo: 1370s
Progresso: 1920/5355 | falhas: 0 | tempo: 1386s
Progresso: 1930/5355 | falhas: 0 | tempo: 1390s
Progresso: 1980/5355 | falhas: 0 | tempo: 1443s
Progresso: 1990/5355 | falhas: 0 | tempo: 1455s
Progresso: 2000/5355 | falhas: 0 | tempo: 1460s
Progresso: 2010/5355 | falhas: 0 | tempo: 1464s
Progresso: 2030/5355 | falhas: 0 | tempo: 1506s
Progresso: 2090/5355 | falhas: 0 | tempo: 1530s
Progresso: 2110/5355 | falhas: 0 | tempo: 1544s
Progresso: 2140/5355 | falhas: 0 | tempo: 1565s
Progresso: 2170/5355 | falhas: 0 | tempo: 1579s
Progresso: 2200/5355 | falhas: 0 | tempo: 1595s
Progresso: 2210/5355 | falhas: 0 | tempo: 1600s
Progresso: 2230/5355 | falhas: 0 | tempo: 1614s
Progresso: 2270/5355 | falhas: 0 | tempo: 1651s
Progresso: 2310/5355 | falhas: 0 | tempo: 1686s
Progresso: 2330/5355 | falhas: 0 | tempo: 1694s
Progresso: 2340/5355 | falhas: 0 | tempo: 1699s
Progresso: 2430/5355 | falhas: 0 | tempo: 1778s
Progresso: 2530/5355 | falhas: 0 | tempo: 1838s
Progresso: 2550/5355 | falhas: 0 | tempo: 1862s
Progresso: 2570/5355 | falhas: 0 | tempo: 1880s
Progresso: 2620/5355 | falhas: 0 | tempo: 1904s
Progresso: 2680/5355 | falhas: 0 | tempo: 1921s
Progresso: 2710/5355 | falhas: 0 | tempo: 1942s
Progresso: 2720/5355 | falhas: 0 | tempo: 1947s
Progresso: 2730/5355 | falhas: 0 | tempo: 1956s
Progresso: 2740/5355 | falhas: 0 | tempo: 1961s
Progresso: 2750/5355 | falhas: 0 | tempo: 1963s
Progresso: 2760/5355 | falhas: 0 | tempo: 1970s
Progresso: 2780/5355 | falhas: 0 | tempo: 1975s
Progresso: 2790/5355 | falhas: 0 | tempo: 1991s
Progresso: 2870/5355 | falhas: 0 | tempo: 2046s
Progresso: 2890/5355 | falhas: 0 | tempo: 2060s
Progresso: 2940/5355 | falhas: 0 | tempo: 2083s
Progresso: 2950/5355 | falhas: 0 | tempo: 2088s
Progresso: 3010/5355 | falhas: 0 | tempo: 2131s
Progresso: 3080/5355 | falhas: 0 | tempo: 2165s
Progresso: 3090/5355 | falhas: 0 | tempo: 2177s
Progresso: 3110/5355 | falhas: 0 | tempo: 2223s
Progresso: 3160/5355 | falhas: 0 | tempo: 2242s
Progresso: 3240/5355 | falhas: 0 | tempo: 2272s
Progresso: 3260/5355 | falhas: 0 | tempo: 2291s
Progresso: 3270/5355 | falhas: 0 | tempo: 2307s
Progresso: 3280/5355 | falhas: 0 | tempo: 2316s
Progresso: 3310/5355 | falhas: 0 | tempo: 2353s
Progresso: 3340/5355 | falhas: 0 | tempo: 2387s
Progresso: 3380/5355 | falhas: 0 | tempo: 2406s
Progresso: 3390/5355 | falhas: 0 | tempo: 2423s
Progresso: 3470/5355 | falhas: 0 | tempo: 2468s
Progresso: 3520/5355 | falhas: 0 | tempo: 2502s
Progresso: 3560/5355 | falhas: 0 | tempo: 2532s
Progresso: 3570/5355 | falhas: 0 | tempo: 2541s
Progresso: 3600/5355 | falhas: 0 | tempo: 2551s
Progresso: 3630/5355 | falhas: 0 | tempo: 2570s
Progresso: 3640/5355 | falhas: 0 | tempo: 2576s
Progresso: 3650/5355 | falhas: 0 | tempo: 2582s
Progresso: 3690/5355 | falhas: 0 | tempo: 2596s
Progresso: 3710/5355 | falhas: 0 | tempo: 2605s
Progresso: 3730/5355 | falhas: 0 | tempo: 2617s
Progresso: 3740/5355 | falhas: 0 | tempo: 2626s
Progresso: 3760/5355 | falhas: 0 | tempo: 2630s
Progresso: 3780/5355 | falhas: 0 | tempo: 2634s
Progresso: 3790/5355 | falhas: 0 | tempo: 2643s
Progresso: 3800/5355 | falhas: 0 | tempo: 2657s
Progresso: 3820/5355 | falhas: 0 | tempo: 2675s
Progresso: 3830/5355 | falhas: 0 | tempo: 2684s
Progresso: 3880/5355 | falhas: 0 | tempo: 2725s
Progresso: 3960/5355 | falhas: 0 | tempo: 2766s
Progresso: 3970/5355 | falhas: 0 | tempo: 2769s
Progresso: 4000/5355 | falhas: 0 | tempo: 2792s
Progresso: 4010/5355 | falhas: 0 | tempo: 2795s
Progresso: 4050/5355 | falhas: 0 | tempo: 2851s
Progresso: 4250/5355 | falhas: 0 | tempo: 2958s
Progresso: 4280/5355 | falhas: 0 | tempo: 2967s
Progresso: 4330/5355 | falhas: 0 | tempo: 2999s
Progresso: 4340/5355 | falhas: 0 | tempo: 3007s
Progresso: 4370/5355 | falhas: 0 | tempo: 3023s
Progresso: 4400/5355 | falhas: 0 | tempo: 3036s
Progresso: 4460/5355 | falhas: 0 | tempo: 3111s
Progresso: 4550/5355 | falhas: 0 | tempo: 3145s
Progresso: 4570/5355 | falhas: 0 | tempo: 3154s
Progresso: 4600/5355 | falhas: 0 | tempo: 3161s
Progresso: 4610/5355 | falhas: 0 | tempo: 3164s
Progresso: 4640/5355 | falhas: 0 | tempo: 3175s
Progresso: 4660/5355 | falhas: 0 | tempo: 3187s
Progresso: 4680/5355 | falhas: 0 | tempo: 3195s
Progresso: 4720/5355 | falhas: 0 | tempo: 3208s
Progresso: 4740/5355 | falhas: 0 | tempo: 3213s
Progresso: 4750/5355 | falhas: 0 | tempo: 3216s
Progresso: 4780/5355 | falhas: 0 | tempo: 3237s
Progresso: 4820/5355 | falhas: 0 | tempo: 3271s
Progresso: 4880/5355 | falhas: 0 | tempo: 3296s
Progresso: 4900/5355 | falhas: 0 | tempo: 3309s
Progresso: 4960/5355 | falhas: 0 | tempo: 3325s
Progresso: 5070/5355 | falhas: 0 | tempo: 3353s
Progresso: 5080/5355 | falhas: 0 | tempo: 3356s
Progresso: 5100/5355 | falhas: 0 | tempo: 3385s
Progresso: 5110/5355 | falhas: 0 | tempo: 3386s
Progresso: 5250/5355 | falhas: 0 | tempo: 3447s
Progresso: 5270/5355 | falhas: 0 | tempo: 3457s
Progresso: 5300/5355 | falhas: 0 | tempo: 3472s
Progresso: 5310/5355 | falhas: 0 | tempo: 3473s
Progresso: 5350/5355 | falhas: 0 | tempo: 3502s
Progresso: 5360/5355 | falhas: 0 | tempo: 3510s
Progresso: 5380/5355 | falhas: 0 | tempo: 3515s
Progresso: 5430/5355 | falhas: 0 | tempo: 3536s
Progresso: 5450/5355 | falhas: 0 | tempo: 3551s
Progresso: 5460/5355 | falhas: 0 | tempo: 3569s
Progresso: 5490/5355 | falhas: 0 | tempo: 3579s
Progresso: 5590/5355 | falhas: 0 | tempo: 3622s
Progresso: 5630/5355 | falhas: 0 | tempo: 3629s
Progresso: 5640/5355 | falhas: 0 | tempo: 3636s
Progresso: 5660/5355 | falhas: 0 | tempo: 3651s
Progresso: 5680/5355 | falhas: 0 | tempo: 3659s
Progresso: 5770/5355 | falhas: 0 | tempo: 3697s
Progresso: 6040/5355 | falhas: 0 | tempo: 3783s
Progresso: 6060/5355 | falhas: 0 | tempo: 3789s
Progresso: 6080/5355 | falhas: 0 | tempo: 3795s
Progresso: 6090/5355 | falhas: 0 | tempo: 3797s
Progresso: 6150/5355 | falhas: 0 | tempo: 3833s
Progresso: 6250/5355 | falhas: 0 | tempo: 3842s
Progresso: 6260/5355 | falhas: 0 | tempo: 3845s
Progresso: 6270/5355 | falhas: 0 | tempo: 3851s
Progresso: 6360/5355 | falhas: 0 | tempo: 3899s
Progresso: 6420/5355 | falhas: 0 | tempo: 3932s
Progresso: 6430/5355 | falhas: 0 | tempo: 3936s
Progresso: 6500/5355 | falhas: 0 | tempo: 3957s
Progresso: 6510/5355 | falhas: 0 | tempo: 3958s
Progresso: 6520/5355 | falhas: 0 | tempo: 3961s
Progresso: 6530/5355 | falhas: 0 | tempo: 3962s
Progresso: 6540/5355 | falhas: 0 | tempo: 3975s
Progresso: 6560/5355 | falhas: 0 | tempo: 3990s
Progresso: 6580/5355 | falhas: 0 | tempo: 4015s
Progresso: 6640/5355 | falhas: 0 | tempo: 4054s
Progresso: 6650/5355 | falhas: 0 | tempo: 4061s
Progresso: 6710/5355 | falhas: 0 | tempo: 4071s
Progresso: 6720/5355 | falhas: 0 | tempo: 4093s
Progresso: 6770/5355 | falhas: 0 | tempo: 4143s
Progresso: 6780/5355 | falhas: 0 | tempo: 4159s
Progresso: 6910/5355 | falhas: 0 | tempo: 4226s
Progresso: 6920/5355 | falhas: 0 | tempo: 4230s
Progresso: 7020/5355 | falhas: 0 | tempo: 4267s
Progresso: 7080/5355 | falhas: 0 | tempo: 4337s
Progresso: 7120/5355 | falhas: 0 | tempo: 4349s
Progresso: 7130/5355 | falhas: 0 | tempo: 4355s
Progresso: 7140/5355 | falhas: 0 | tempo: 4376s
Progresso: 7180/5355 | falhas: 0 | tempo: 4383s
Progresso: 7340/5355 | falhas: 0 | tempo: 4445s
Progresso: 7440/5355 | falhas: 0 | tempo: 4456s
Progresso: 7640/5355 | falhas: 0 | tempo: 4513s
Progresso: 7720/5355 | falhas: 0 | tempo: 4544s
Progresso: 7760/5355 | falhas: 0 | tempo: 4559s
Progresso: 7790/5355 | falhas: 0 | tempo: 4568s
Progresso: 7820/5355 | falhas: 0 | tempo: 4577s
Progresso: 7960/5355 | falhas: 0 | tempo: 4600s
Progresso: 8060/5355 | falhas: 0 | tempo: 4656s
Progresso: 8070/5355 | falhas: 0 | tempo: 4672s
Progresso: 8090/5355 | falhas: 0 | tempo: 4684s
Progresso: 8100/5355 | falhas: 0 | tempo: 4691s
Progresso: 8110/5355 | falhas: 0 | tempo: 4697s
Progresso: 8120/5355 | falhas: 0 | tempo: 4708s
Progresso: 8140/5355 | falhas: 0 | tempo: 4739s
Progresso: 8540/5355 | falhas: 0 | tempo: 4792s
Progresso: 8610/5355 | falhas: 0 | tempo: 4795s
Progresso: 8720/5355 | falhas: 0 | tempo: 4816s
Progresso: 8870/5355 | falhas: 0 | tempo: 4851s
Progresso: 8960/5355 | falhas: 0 | tempo: 4855s
Progresso: 9110/5355 | falhas: 0 | tempo: 4861s
Progresso: 9130/5355 | falhas: 0 | tempo: 4861s
Progresso: 9180/5355 | falhas: 0 | tempo: 4869s
Progresso: 9190/5355 | falhas: 0 | tempo: 4871s
Progresso: 9200/5355 | falhas: 0 | tempo: 4872s
Progresso: 9220/5355 | falhas: 0 | tempo: 4875s
Progresso: 9240/5355 | falhas: 0 | tempo: 4879s
Progresso: 9320/5355 | falhas: 0 | tempo: 4935s
Progresso: 9410/5355 | falhas: 0 | tempo: 4965s
Progresso: 9460/5355 | falhas: 0 | tempo: 4977s
Progresso: 9520/5355 | falhas: 0 | tempo: 4994s
Progresso: 9640/5355 | falhas: 0 | tempo: 5032s
Progresso: 9750/5355 | falhas: 0 | tempo: 5055s
Progresso: 9840/5355 | falhas: 0 | tempo: 5079s
Progresso: 9880/5355 | falhas: 0 | tempo: 5103s
Progresso: 9970/5355 | falhas: 0 | tempo: 5123s
Progresso: 10060/5355 | falhas: 0 | tempo: 5157s
Progresso: 10110/5355 | falhas: 0 | tempo: 5180s
Progresso: 10150/5355 | falhas: 0 | tempo: 5191s
Progresso: 10170/5355 | falhas: 0 | tempo: 5199s
Progresso: 10220/5355 | falhas: 0 | tempo: 5221s
Progresso: 10260/5355 | falhas: 0 | tempo: 5236s
Progresso: 10360/5355 | falhas: 0 | tempo: 5274s
Progresso: 10410/5355 | falhas: 0 | tempo: 5286s
Progresso: 10460/5355 | falhas: 0 | tempo: 5298s
Progresso: 10500/5355 | falhas: 0 | tempo: 5313s
Progresso: 10540/5355 | falhas: 0 | tempo: 5352s
Progresso: 10550/5355 | falhas: 0 | tempo: 5359s
Progresso: 10570/5355 | falhas: 0 | tempo: 5365s
Progresso: 10580/5355 | falhas: 0 | tempo: 5368s
Progresso: 10590/5355 | falhas: 0 | tempo: 5372s
Progresso: 10660/5355 | falhas: 0 | tempo: 5412s
Progresso: 10690/5355 | falhas: 0 | tempo: 5423s
Progresso: 10780/5355 | falhas: 0 | tempo: 5466s
Progresso: 10790/5355 | falhas: 0 | tempo: 5467s
Progresso: 10800/5355 | falhas: 0 | tempo: 5477s
Progresso: 10910/5355 | falhas: 0 | tempo: 5522s
Progresso: 10950/5355 | falhas: 0 | tempo: 5531s
Progresso: 10970/5355 | falhas: 0 | tempo: 5543s
Progresso: 10980/5355 | falhas: 0 | tempo: 5562s
Progresso: 11000/5355 | falhas: 0 | tempo: 5574s
Progresso: 11010/5355 | falhas: 0 | tempo: 5574s
Progresso: 11020/5355 | falhas: 0 | tempo: 5582s
Progresso: 11040/5355 | falhas: 0 | tempo: 5597s
Progresso: 11070/5355 | falhas: 0 | tempo: 5617s
Progresso: 11080/5355 | falhas: 0 | tempo: 5624s
Progresso: 11100/5355 | falhas: 0 | tempo: 5633s
Progresso: 11130/5355 | falhas: 0 | tempo: 5643s
Progresso: 11150/5355 | falhas: 0 | tempo: 5650s
Progresso: 11160/5355 | falhas: 0 | tempo: 5674s
Progresso: 11180/5355 | falhas: 0 | tempo: 5680s
Progresso: 11230/5355 | falhas: 0 | tempo: 5717s
Progresso: 11240/5355 | falhas: 0 | tempo: 5720s
Progresso: 11290/5355 | falhas: 0 | tempo: 5737s
Progresso: 11330/5355 | falhas: 0 | tempo: 5765s
Progresso: 11370/5355 | falhas: 0 | tempo: 5785s
Progresso: 11390/5355 | falhas: 0 | tempo: 5800s
Progresso: 11430/5355 | falhas: 0 | tempo: 5811s
Progresso: 11450/5355 | falhas: 0 | tempo: 5815s
Progresso: 11460/5355 | falhas: 0 | tempo: 5819s
Progresso: 11480/5355 | falhas: 0 | tempo: 5837s
Progresso: 11490/5355 | falhas: 0 | tempo: 5842s
Progresso: 11500/5355 | falhas: 0 | tempo: 5846s
Progresso: 11640/5355 | falhas: 0 | tempo: 5905s
Progresso: 11700/5355 | falhas: 0 | tempo: 5943s
Progresso: 11710/5355 | falhas: 0 | tempo: 5963s
Progresso: 11780/5355 | falhas: 0 | tempo: 5992s
Progresso: 11800/5355 | falhas: 0 | tempo: 6006s
Progresso: 11830/5355 | falhas: 0 | tempo: 6030s
Progresso: 11840/5355 | falhas: 0 | tempo: 6033s
Progresso: 11860/5355 | falhas: 0 | tempo: 6038s
Progresso: 11890/5355 | falhas: 0 | tempo: 6051s
Progresso: 11920/5355 | falhas: 0 | tempo: 6062s
Progresso: 11960/5355 | falhas: 0 | tempo: 6079s
Progresso: 12030/5355 | falhas: 0 | tempo: 6108s
Progresso: 12040/5355 | falhas: 0 | tempo: 6108s
Progresso: 12050/5355 | falhas: 0 | tempo: 6118s
Progresso: 12110/5355 | falhas: 0 | tempo: 6142s
Progresso: 12130/5355 | falhas: 0 | tempo: 6155s
Progresso: 12230/5355 | falhas: 0 | tempo: 6214s
Progresso: 12290/5355 | falhas: 0 | tempo: 6244s
Progresso: 12350/5355 | falhas: 0 | tempo: 6252s
Progresso: 12420/5355 | falhas: 0 | tempo: 6278s
Progresso: 12450/5355 | falhas: 0 | tempo: 6288s
Progresso: 12460/5355 | falhas: 0 | tempo: 6298s
Progresso: 12470/5355 | falhas: 0 | tempo: 6316s
Progresso: 12490/5355 | falhas: 0 | tempo: 6330s
Progresso: 12540/5355 | falhas: 0 | tempo: 6349s
Progresso: 12560/5355 | falhas: 0 | tempo: 6358s
Progresso: 12610/5355 | falhas: 0 | tempo: 6393s
Progresso: 12680/5355 | falhas: 0 | tempo: 6412s
Progresso: 12690/5355 | falhas: 0 | tempo: 6423s
Progresso: 12710/5355 | falhas: 0 | tempo: 6423s
Progresso: 12740/5355 | falhas: 0 | tempo: 6430s
Progresso: 12780/5355 | falhas: 0 | tempo: 6446s
Progresso: 12870/5355 | falhas: 0 | tempo: 6472s
Progresso: 12920/5355 | falhas: 0 | tempo: 6495s
Progresso: 13080/5355 | falhas: 0 | tempo: 6530s
Progresso: 13130/5355 | falhas: 0 | tempo: 6548s
Progresso: 13220/5355 | falhas: 0 | tempo: 6560s
Progresso: 13310/5355 | falhas: 0 | tempo: 6583s
Progresso: 13320/5355 | falhas: 0 | tempo: 6585s
Progresso: 13410/5355 | falhas: 0 | tempo: 6601s
Progresso: 13480/5355 | falhas: 0 | tempo: 6620s
Progresso: 13540/5355 | falhas: 0 | tempo: 6635s
Progresso: 13580/5355 | falhas: 0 | tempo: 6648s
Progresso: 13630/5355 | falhas: 0 | tempo: 6669s
Progresso: 13760/5355 | falhas: 0 | tempo: 6717s
Progresso: 13860/5355 | falhas: 0 | tempo: 6759s
Progresso: 13870/5355 | falhas: 0 | tempo: 6770s
Progresso: 13930/5355 | falhas: 0 | tempo: 6789s
Progresso: 13940/5355 | falhas: 0 | tempo: 6795s
Progresso: 13970/5355 | falhas: 0 | tempo: 6795s
Progresso: 14180/5355 | falhas: 0 | tempo: 6849s
Progresso: 14260/5355 | falhas: 0 | tempo: 6888s
Progresso: 14280/5355 | falhas: 0 | tempo: 6896s
Progresso: 14300/5355 | falhas: 0 | tempo: 6906s
Progresso: 14320/5355 | falhas: 0 | tempo: 6911s
Progresso: 14330/5355 | falhas: 0 | tempo: 6917s
Progresso: 14390/5355 | falhas: 0 | tempo: 6924s
Progresso: 14460/5355 | falhas: 0 | tempo: 6940s
Progresso: 14830/5355 | falhas: 0 | tempo: 7029s
Progresso: 14900/5355 | falhas: 0 | tempo: 7052s
Progresso: 14940/5355 | falhas: 0 | tempo: 7071s
Progresso: 15060/5355 | falhas: 0 | tempo: 7110s
Progresso: 15260/5355 | falhas: 0 | tempo: 7171s
Progresso: 15320/5355 | falhas: 0 | tempo: 7177s
Progresso: 15330/5355 | falhas: 0 | tempo: 7183s
Progresso: 15470/5355 | falhas: 0 | tempo: 7217s
Progresso: 15810/5355 | falhas: 0 | tempo: 7308s
Progresso: 15830/5355 | falhas: 0 | tempo: 7317s
Progresso: 15910/5355 | falhas: 0 | tempo: 7336s
Progresso: 15940/5355 | falhas: 0 | tempo: 7339s
Progresso: 15950/5355 | falhas: 0 | tempo: 7341s
Progresso: 16020/5355 | falhas: 0 | tempo: 7365s
Progresso: 16040/5355 | falhas: 0 | tempo: 7371s
Progresso: 16070/5355 | falhas: 0 | tempo: 7379s
Progresso: 16080/5355 | falhas: 0 | tempo: 7394s
Progresso: 16380/5355 | falhas: 0 | tempo: 7461s
Progresso: 16510/5355 | falhas: 0 | tempo: 7490s
Progresso: 16560/5355 | falhas: 0 | tempo: 7499s
Progresso: 16690/5355 | falhas: 0 | tempo: 7524s
Progresso: 16730/5355 | falhas: 0 | tempo: 7545s
Progresso: 16850/5355 | falhas: 0 | tempo: 7573s
Progresso: 16860/5355 | falhas: 0 | tempo: 7581s
Progresso: 16980/5355 | falhas: 0 | tempo: 7607s
Progresso: 16990/5355 | falhas: 0 | tempo: 7613s
Progresso: 17010/5355 | falhas: 0 | tempo: 7624s
Progresso: 17020/5355 | falhas: 0 | tempo: 7625s
Progresso: 17050/5355 | falhas: 0 | tempo: 7635s
Progresso: 17100/5355 | falhas: 0 | tempo: 7653s
Progresso: 17150/5355 | falhas: 0 | tempo: 7670s
Progresso: 17230/5355 | falhas: 0 | tempo: 7702s
Progresso: 17260/5355 | falhas: 0 | tempo: 7715s
Progresso: 17290/5355 | falhas: 0 | tempo: 7726s
Progresso: 17370/5355 | falhas: 0 | tempo: 7740s
Progresso: 17450/5355 | falhas: 0 | tempo: 7754s
Progresso: 17490/5355 | falhas: 0 | tempo: 7779s
Progresso: 17510/5355 | falhas: 0 | tempo: 7782s
Progresso: 17530/5355 | falhas: 0 | tempo: 7784s
Progresso: 17540/5355 | falhas: 0 | tempo: 7787s
Progresso: 17650/5355 | falhas: 0 | tempo: 7825s
Progresso: 17820/5355 | falhas: 0 | tempo: 7883s
Progresso: 17850/5355 | falhas: 0 | tempo: 7886s
Progresso: 17890/5355 | falhas: 0 | tempo: 7905s
Progresso: 17930/5355 | falhas: 0 | tempo: 7927s
Progresso: 17950/5355 | falhas: 0 | tempo: 7932s
Progresso: 17970/5355 | falhas: 0 | tempo: 7944s
Progresso: 18030/5355 | falhas: 0 | tempo: 7954s
Progresso: 18040/5355 | falhas: 0 | tempo: 7957s

In [70]:
# Visualizando como ficou o dataframe da API
df_api.head()

,id,franquia,is_franchise,estudio_principal,original_language,production_countries
0,862,Toy Story Collection,True,Pixar,en,United States of America
1,8844,Jumanji Collection,True,TriStar Pictures,en,United States of America
2,31357,Sem franquia,False,20th Century Fox,en,United States of America
3,949,Heat Collection,True,Warner Bros. Pictures,en,United States of America
4,9091,Sem franquia,False,Shattered Productions,en,United States of America

In [69]:
df_api = df_api.drop(columns=['status'])

In [66]:
df_api.isnull().sum()

id                      0
franquia                0
is_franchise            0
estudio_principal       0
original_language       0
production_countries    0
status                  0
dtype: int64

In [75]:
df_api['franquia'] = df_api['franquia'].fillna('Sem franquia')

df_api['estudio_principal'] = df_api['estudio_principal'].fillna('Não informado')

df_api['production_countries'] = df_api['production_countries'].fillna('Não informado')

df_api.isnull().sum()

id                      0
franquia                0
is_franchise            0
estudio_principal       0
original_language       0
production_countries    0
dtype: int64

In [71]:
# Merge final usando o id do TMDB como chave
df_final = pd.merge(df_final, df_api, on="id", how="left")

In [74]:
# Visualizando como ficou o dataframe da API
df_final.head()

,id,imdb_id,title,budget,revenue,release_date,runtime,popularity,averageRating,numVotes,genres,franquia,is_franchise,estudio_principal,original_language,production_countries
0,862,tt0114709,Toy Story,30000000.0,373554033.0,1995-10-30,81.0,21.946943,8.3,1176535,"Adventure,Animation,Comedy",Toy Story Collection,True,Pixar,en,United States of America
1,8844,tt0113497,Jumanji,65000000.0,262797249.0,1995-12-15,104.0,17.015539,7.1,414470,"Adventure,Comedy,Family",Jumanji Collection,True,TriStar Pictures,en,United States of America
2,31357,tt0114885,Waiting to Exhale,16000000.0,81452156.0,1995-12-22,127.0,3.859495,6.0,14008,"Comedy,Drama,Romance",Sem franquia,False,20th Century Fox,en,United States of America
3,949,tt0113277,Heat,60000000.0,187436818.0,1995-12-15,170.0,17.924927,8.3,806505,"Action,Crime,Drama",Heat Collection,True,Warner Bros. Pictures,en,United States of America
4,9091,tt0114576,Sudden Death,35000000.0,64350171.0,1995-12-22,106.0,5.231580,5.9,39661,"Action,Crime,Thriller",Sem franquia,False,Shattered Productions,en,United States of America